name: abass_news
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  # Database
  postgres: ^2.6.3
  # Authentication & Security
  jwt_decoder: ^2.0.1
  crypto: ^3.0.3
  # JSON handling
  json_annotation: ^4.9.0
  # Validation
  freezed_annotation: ^2.4.1
  # Environment variables
  dart_define: ^2.0.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  analyzer: ^5.13.0
