[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production" 